routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify'=>true]);

Route::get('/home', 'HomeController@index')->name('home')
;
Route::get('/admin/index', 'Admin\DashboardController@index')->name('admin.index')
;

Route::get('/admin/users/index', 'Admin\UsersController@index')->name('admin.users.index')
;
Route::get('/admin/users/{user}/edit', 'Admin\UsersController@edit')->name('admin.users.edit')
;
Route::put('/admin/users/{user}/update', 'Admin\UsersController@update')->name('admin.users.update')
;
Route::get('/admin/users/destroy', 'Admin\UsersController@destroy')->name('admin.users.destroy')
;
Route::get('/admin/users/create', 'Admin\UsersController@create')->name('admin.users.create')
;

Route::get('/admin/ships/index', 'Admin\ShipsController@index')->name('admin.ships.index')
;
Route::get('/admin/ships/{ship}/edit', 'Admin\ShipsController@edit')->name('admin.ships.edit')
;
Route::put('/admin/ships/{ship}/update', 'Admin\ShipsController@update')->name('admin.ships.update')
;
Route::get('/admin/ships/destroy', 'Admin\ShipsController@destroy')->name('admin.ships.destroy')
;
Route::get('/admin/ships/create', 'Admin\ShipsController@create')->name('admin.ships.create')
;

Route::get('/admin/roles/index', 'Admin\RolesController@index')->name('admin.roles.index')
;
Route::get('/admin/roles/{role}/edit', 'Admin\RolesController@edit')->name('admin.roles.edit')
;
Route::put('/admin/roles/{role}/update', 'Admin\RolesController@update')->name('admin.roles.update')
;
Route::get('/admin/roles/destroy', 'Admin\RolesController@destroy')->name('admin.roles.destroy')
;
Route::get('/admin/roles/create', 'Admin\RolesController@create')->name('admin.roles.create')
;


Route::get('/admin/notifications/create', 'Admin\NotificationsController@create')->name('admin.notifications.create')
;

Route::post('/home/{id}', 'HomeController@markAsRead', function($id){})->name('markAsRead')
;
//Route::get('/password', 'Admin\UsersController@inputPassword')->name('password');

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function(){

	Route::resource('/users', 'UsersController');
	Route::resource('/ships', 'ShipsController');
	Route::resource('/roles', 'RolesController');
	Route::resource('/notifications', 'NotificationsController');

});

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{

	protected $fillable = [
		'name'
	];

    public function users(){
        return $this->hasMany('App\User');
    }

    public function notifications()
    {
        return $this->belongsToMany(Notification::class);
    }
}

app/Http/Controllers/Admin/RolesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Role;

class RolesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $roles = Role::where('name', '!=', 'admin')->get();
        return view ('admin.roles.index')->with('roles', $roles);
    }


    public function create()
    {

        return view('admin.roles.create');
    }

    public function store(Request $request)
    {
        $role = new Role();
        $role->name = $request->input('name');

  		
        $role->save();


         return redirect()->route('admin.roles.index');
    }

    public function edit(Role $role)
    {

        return view('admin.roles.edit')->with([

            'role' => $role


        ]);
    }

    public function update(Request $request, Role $role)
    {
        $role->name = $request->input('name');

  

        $role->save();

        return redirect()->route('admin.roles.index');
    }

    public function destroy(Role $role)
    {

        $role->delete();

        return redirect()->route('admin.roles.index');
    }
}

resources/views/admin/roles/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <br><br>
        <div class="row" style="width:800px;">
            <div class="card col s12 m8 offset-m2 l8 offset-l2 xl8 offset-xl2 card-mt-15"  >
                <h4 class="center grey-text text-darken-2 card-title">Add a new role</h4>
                <div class="card-content" style="width: 32%; margin: 0 auto;">
                    <div class="row">
                       
                        <form action="{{route('admin.roles.store')}}" method="POST">
                            <div class="input-field no-margin">
                            <i class="material-icons prefix">account_balance</i>
                     
                                <input type="text" name="name" id="name" class="validate" value="{{ Request::old('name') ? : '' }}">
                                <label for="name">Name</label>

                                
                                <span class="{{$errors->has('name') ? 'helper-text red-text' : '' }}">{{$errors->first('name')}}</span>
                            </div>
                            <br>
                            
                                            
                            @csrf()
                            <button type="submit" class="btn waves-effect waves-light mt-15 col s6 offset-s3 m4 offset-m4 l4 offset-l4 xl4-offset-xl4">Add</button>
                        </form>
                    </div>
                </div>
                
                <script>
            $('#image').on('change',function(){
                //get the file name
                var fileName = $(this).val();
                //replace the "Choose a file" label
                $(this).next('.custom-file-label').html(fileName);
            })
        </script>

                <div class="card-action">
                    <a href="{{route('admin.roles.index')}}">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <br><br>
        <div class="row" style="width:800px;">
            <div class="card col s12 m8 offset-m2 l8 offset-l2 xl8 offset-xl2 card-mt-15"  >
                <h4 class="center grey-text text-darken-2 card-title">Edit role {{$role->name}}</h4>
                <div class="card-content" style="width: 32%; margin: 0 auto;">
                    <div class="row">
                       
                        <form action="{{route('admin.roles.update', $role)}}" method="POST">
                            <div class="input-field no-margin">
                            <i class="material-icons prefix">account_balance</i>
                     
                                <input type="text" name="name" id="name" class="validate" value="{{ $role->name }}">
                                <label for="name">Name</label>

                                
                                <span class="{{$errors->has('name') ? 'helper-text red-text' : '' }}">{{$errors->first('name')}}</span>
                            </div>
                            <br>
                            
                            @method('PUT')                
                            @csrf()
                            <button type="submit" class="btn waves-effect waves-light mt-15 col s6 offset-s3 m4 offset-m4 l4 offset-l4 xl4-offset-xl4">Store</button>
                        </form>
                    </div>
                </div>
                
                <div class="card-action">
                    <a href="{{route('admin.roles.index')}}">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <h4 class="black-text text-darken-1 center">Ranks</h4>
    
    <div class="row justify-content-center" >
  
        <div class="card col s4 m4 l xl4">
            <div class="card-content">
                <div class="row">
            
                    <br>
                    <table class="responsive-table col s8 m8 l8 xl8">
                        <thead class="grey-text text-darken-2">
                            <tr>

                                <th class="center">Name</th>
                                <th class="center">Actions</th>
                            </tr>
                        </thead>
                        <tbody id="dept-table">
                            
                            @if($roles->count())
                                @foreach($roles as $role)
                                    <tr>
                                        <td class="center">{{$role->name}}</td>
                                        <td class="center">
                                            <div class="row mb-0">
                                              <div class="col">
              
                                                    <a href="{{route('admin.roles.edit',$role->id)}}" class="btn btn-floating btn-small waves=effect waves-light orange"><i class="material-icons">mode_edit</i></a>
                                                </div>
                                                <div class="col">

                                                    <form action="{{route('admin.roles.destroy',$role->id)}}" method="POST">
                    
                                                        @method('DELETE')

                                                        @csrf()
                                                        <button type="submit" class="btn btn-floating btn-small waves=effect waves-light red"><i class="material-icons">delete</i></button>
                                                    </form>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                              
                                <tr>
                                    <td colspan="5"><h6 class="grey-text text-darken-2 center">There are no roles.</h6></td>
                                </tr>
                            @endif

                        </tbody>
                    </table>

                </div>

            </div>
        </div>
        <!-- Card END -->
    </div>
</div>


<div class="fixed-action-btn">
    <a class="btn-floating btn-large waves=effect waves-light red" href="{{route('admin.roles.create')}}">
        <i class="large material-icons">add</i>
    </a>
</div> 
@endsection