routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify'=>true]);

Route::get('/home', 'HomeController@index')->name('home')
;
Route::get('/admin/index', 'Admin\DashboardController@index')->name('admin.index')
;

Route::get('/admin/users/index', 'Admin\UsersController@index')->name('admin.users.index')
;
Route::get('/admin/users/{user}/edit', 'Admin\UsersController@edit')->name('admin.users.edit')
;
Route::put('/admin/users/{user}/update', 'Admin\UsersController@update')->name('admin.users.update')
;
Route::get('/admin/users/destroy', 'Admin\UsersController@destroy')->name('admin.users.destroy')
;
Route::get('/admin/users/create', 'Admin\UsersController@create')->name('admin.users.create')
;

Route::get('/admin/ships/index', 'Admin\ShipsController@index')->name('admin.ships.index')
;
Route::get('/admin/ships/{ship}/edit', 'Admin\ShipsController@edit')->name('admin.ships.edit')
;
Route::put('/admin/ships/{ship}/update', 'Admin\ShipsController@update')->name('admin.ships.update')
;
Route::get('/admin/ships/destroy', 'Admin\ShipsController@destroy')->name('admin.ships.destroy')
;
Route::get('/admin/ships/create', 'Admin\ShipsController@create')->name('admin.ships.create')
;

Route::get('/admin/roles/index', 'Admin\RolesController@index')->name('admin.roles.index')
;
Route::get('/admin/roles/{role}/edit', 'Admin\RolesController@edit')->name('admin.roles.edit')
;
Route::put('/admin/roles/{role}/update', 'Admin\RolesController@update')->name('admin.roles.update')
;
Route::get('/admin/roles/destroy', 'Admin\RolesController@destroy')->name('admin.roles.destroy')
;
Route::get('/admin/roles/create', 'Admin\RolesController@create')->name('admin.roles.create')
;


Route::get('/admin/notifications/create', 'Admin\NotificationsController@create')->name('admin.notifications.create')
;

Route::post('/home/{id}', 'HomeController@markAsRead', function($id){})->name('markAsRead')
;
//Route::get('/password', 'Admin\UsersController@inputPassword')->name('password');

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function(){

	Route::resource('/users', 'UsersController');
	Route::resource('/ships', 'ShipsController');
	Route::resource('/roles', 'RolesController');
	Route::resource('/notifications', 'NotificationsController');

});

app/Notification.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;

class Notification extends Model
{
    public function user()
    {
        return $this->belongsToMany(User::class)->withPivot('read_at');
    }


    public function role()
    {
        return $this->belongsToMany(Role::class);
    }

}

app/Http/Controllers/Admin/NotificationsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Role;
use App\User;
use App\Notification;

class NotificationsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }


    public function create()
    {
        $roles = Role::orderBy('name','asc')->get();

        return view('admin.notifications.create')->with([
            'roles' => $roles
        ]);
    }


    public function store(Request $request)
    {
        $notificaion = new Notification();
        $notificaion->content = $request->input('content');
        $notificaion->save();


        $roles = $request->input('roles');

        $notificaion->role()->attach($roles);



        $users = User::whereHas('role', static function ($query) use ($roles) {
                    return $query->whereIn('id', $roles);
                })->get('id');
     

        $notificaion->user()->attach($users);
        return redirect()->route('admin.notifications.create');

    }


}

resources/views/admin/notifications/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <h4 class="black-text text-darken-1 center">New notification</h4>
    <div class="row justify-content-center">
        <div class="col-md-8">
              <br>   
            <div class="card">

       

                <div class="card-body">
                  <form action={{route('admin.notifications.store')}} method="POST" enctype="multipart/form-data">
                    @csrf
                   {{method_field('POST')}} 
                      
                    <div class="form-group">
                          <label for="content">Enter notification content here</label>
                          <textarea class="form-control" id="content" name="content" rows="5"></textarea>
                        </div>


                    <!-- <label for="role_id" class="control-label mb-1">Ranks</label>
                        <div class="input-group col-lg-12">
                          <select multiple="multiple" name="role_id" id="role_id" class="form-control">
                            <option value="">Please Select</option>
                            @foreach ($roles as $role)
                              <option value="{{$role->id}}">{{$role->name}}</option>
                            @endforeach
                          </select>
                        </div> -->

                  <div class="form-group">
                      <label for="roles">Select recipient ranks</label>
                      <select multiple class="form-control" id="roles" name="roles[]">
                        
                         @foreach($roles as $role)
                         <option value="{{$role->id}}">
                            {{$role->name}}
                        </option>
                      @endforeach 
                        
                      </select>
                    </div>
                  <!-- <div class="input-field col s12 m12 l12 xl8 offset-xl2">     
                    <div class="form-check form-check-inline" name="roles" id="roles">
                      @foreach($roles as $role)
                            <input class="form-check-input" type="checkbox" id="cb" name="cb" value="$role">
                            <label class="form-check-label" for="cb">{{$role->name}}</label>
                      @endforeach
                    </div>
                  </div> -->
                    

                    <!-- <div class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="option3" disabled>
                            <label class="form-check-label" for="inlineCheckbox3">3 (disabled)</label>
                    </div> -->
                  

                      <button type="submit" class="btn waves-effect waves-light mt-15 col s6 offset-s3 m4 offset-m4 l4 offset-l4 xl4-offset-xl4">Send</button>


                  </form>
                
            </div>
        </div>
    </div>
</div>
@endsection