routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify'=>true]);

Route::get('/home', 'HomeController@index')->name('home')
;
Route::get('/admin/index', 'Admin\DashboardController@index')->name('admin.index')
;

Route::get('/admin/users/index', 'Admin\UsersController@index')->name('admin.users.index')
;
Route::get('/admin/users/{user}/edit', 'Admin\UsersController@edit')->name('admin.users.edit')
;
Route::put('/admin/users/{user}/update', 'Admin\UsersController@update')->name('admin.users.update')
;
Route::get('/admin/users/destroy', 'Admin\UsersController@destroy')->name('admin.users.destroy')
;
Route::get('/admin/users/create', 'Admin\UsersController@create')->name('admin.users.create')
;

Route::get('/admin/ships/index', 'Admin\ShipsController@index')->name('admin.ships.index')
;
Route::get('/admin/ships/{ship}/edit', 'Admin\ShipsController@edit')->name('admin.ships.edit')
;
Route::put('/admin/ships/{ship}/update', 'Admin\ShipsController@update')->name('admin.ships.update')
;
Route::get('/admin/ships/destroy', 'Admin\ShipsController@destroy')->name('admin.ships.destroy')
;
Route::get('/admin/ships/create', 'Admin\ShipsController@create')->name('admin.ships.create')
;

Route::get('/admin/roles/index', 'Admin\RolesController@index')->name('admin.roles.index')
;
Route::get('/admin/roles/{role}/edit', 'Admin\RolesController@edit')->name('admin.roles.edit')
;
Route::put('/admin/roles/{role}/update', 'Admin\RolesController@update')->name('admin.roles.update')
;
Route::get('/admin/roles/destroy', 'Admin\RolesController@destroy')->name('admin.roles.destroy')
;
Route::get('/admin/roles/create', 'Admin\RolesController@create')->name('admin.roles.create')
;


Route::get('/admin/notifications/create', 'Admin\NotificationsController@create')->name('admin.notifications.create')
;

Route::post('/home/{id}', 'HomeController@markAsRead', function($id){})->name('markAsRead')
;
//Route::get('/password', 'Admin\UsersController@inputPassword')->name('password');

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function(){

	Route::resource('/users', 'UsersController');
	Route::resource('/ships', 'ShipsController');
	Route::resource('/roles', 'RolesController');
	Route::resource('/notifications', 'NotificationsController');

});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Contracts\Auth\CanResetPassword;
use App\Notification;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'surname', 'email', 'password', 'ship_id', 'role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function ship(){
        return $this->belongsTo('App\Ship', 'ship_id');
    }

    public function role(){
        return $this->belongsTo('App\Role', 'role_id');
    }

    public function hasRole($role){
        if($this->role()->where('name', $role)->first()){
            return true;
        }
        return false;
    }

    public function notifications()
    {
        return $this->belongsToMany(Notification::class)->withPivot('read_at');
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Gate;
use App\User;
use App\Role;
use App\Ship;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail; 
use DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\URL;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $users = User::all();
        return view ('admin.users.index')->with('users', $users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::orderBy('name','asc')->get();
        $ships = Ship::orderBy('name','asc')->get();

        return view('admin.users.create')->with([
            'roles' => $roles,
            'ships' =>$ships
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public static $createUrlCallback;
    public function store(Request $request)
    {

        $user = new User();

        $user->name = $request->input('name');
        $user->surname = $request->input('surname');
        $user->email = $request->input('email');
        $user->role_id = $request->input('role');
        $user->ship_id = $request->input('ship');
        $to_name = $request->input('name');
        $to_email = $request->input('email');
        
        $token = app('auth.password.broker')->createToken($user);
        if (static::$createUrlCallback) {
            $url = call_user_func(static::$createUrlCallback, $notifiable, $this->token);
        } else {
            $url = url(route('password.reset', [
                'token' => $token,
                'email' => $to_email,
            ], false));
        }

        

        $data = array('name'=>$to_name, "body" => "Test mail", 'url'=>$url);
        

        Mail::send('email', $data, function($message) use ($to_name, $to_email) {
            $message->to($to_email, $to_name)
                ->subject('Registration link');
            $message->from('anjatestprojekat@gmail.com','Admin Team');
        });

        $user->save();

        return redirect()->route('admin.users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        if(Gate::denies('edit-users')){
            return redirect(route('admin.users.index')); 
        }

        $roles = Role::all();
        $ships = Ship::all();

        return view('admin.users.edit')->with([
            'user' => $user,
            'ships' => $ships,
            'roles' => $roles

        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user->name = $request->input('name');
        $user->surname = $request->input('surname');
        $user->email = $request->input('email');
        $user->role_id = $request->input('role');
        $user->ship_id = $request->input('ship');
        $user->save();

        return redirect()->route('admin.users.index');
    }


    public function inputPassword($user)
    {
        return view ('password')->with('user', $user);
    }


    public function updatePassword(Request $request, User $user)
    {
        $user->password = $request->input(Hash::make('password'));
        $user->save();

        return redirect()->route('home');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        if(Gate::denies('delete-users')){
            return redirect(route('admin.users.index')); 
        }

        $user->delete();

        return redirect()->route('admin.users.index');
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="card col-xl s4 m4 offset-m4 l6 offset-l4 xl8 offset-xl6 card-mt-15">
            
                <h4 class="center grey-text text-darken-2 card-title">Add a new crew member</h4>
                <div class="card-content" style="width: 32%; margin: 0 auto;">
                    <div class="row">
                       
                        <form action="{{route('admin.users.store')}}" method="POST">
                            <div class="input-field no-margin">
                            <i class="material-icons prefix">account_balance</i>
                     
                                <input type="text" name="name" id="name" class="validate" value="{{ Request::old('name') ? : '' }}">
                                <label for="name">Name</label>

                                
                                <span class="{{$errors->has('name') ? 'helper-text red-text' : '' }}">{{$errors->first('name')}}</span>
                            </div>

                            <div class="input-field no-margin">
                            <i class="material-icons prefix">account_balance</i>
                     
                                <input type="text" name="surname" id="surname" class="validate" value="{{ Request::old('surname') ? : '' }}">
                                <label for="surname">Surname</label>

                                
                                <span class="{{$errors->has('surname') ? 'helper-text red-text' : '' }}">{{$errors->first('surname')}}</span>
                            </div>

                            <div class="input-field no-margin">
                                <i class="material-icons prefix">email</i>
                                <input type="email" name="email" id="email" value="{{Request::old('email') ? : ''}}">
                                <label for="email">E-mail</label>
                                <span class="{{$errors->has('email') ? 'helper-text red-text' : ''}}">{{$errors->has('email') ? $errors->first('email') : ''}}</span>
                            </div>
                            <br>
                            <div class="input-field no-margin">

                                <select class="selectpicker form-control" name="role" id="role">
                                    <option value="#">Crew member's rank</option>
                                    @foreach($roles as $role)
                                        <option value="{{$role->id}}">{{$role->name}}</option>
                                    @endforeach
                                </select>
                                <!-- <label for="role">Rank</label>  -->
                            </div>
                          <br>  
                            <div class="input-field no-margin">

                                <select class="selectpicker form-control" name="ship" id="ship">
                                    <option value="#">Crew member's ship</option>
                                    @foreach($ships as $ship)
                                        <option value="{{$ship->id}}">{{$ship->name}}</option>
                                    @endforeach
                                </select>
                               <!--  <label for="ship">Ship</label> -->
                            </div>
                            <br>
                            <br>  <br><br><br>                      
                            @csrf()
                            <button type="submit" class="btn waves-effect waves-light mt-15 col s6 offset-s3 m4 offset-m4 l4 offset-l4 xl4-offset-xl4">Add</button>
                        </form>
                    </div>
                </div>
                
                <script>
            $('#image').on('change',function(){
                //get the file name
                var fileName = $(this).val();
                //replace the "Choose a file" label
                $(this).next('.custom-file-label').html(fileName);
            })
        </script>

                <div class="card-action">
                    <a href="{{route('admin.users.index')}}">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="card col-xl s4 m4 offset-m4 l6 offset-l4 xl8 offset-xl6 card-mt-15" >
            
                <h4 class="center grey-text text-darken-2 card-title">Edit {{$user->name}} {{$user->surname}}</h4>
                <div class="card-content" style="width: 32%; margin: 0 auto;">
                    <div class="row">
                       
                        <form action="{{route('admin.users.update', $user)}}" method="POST">
                            <div class="input-field no-margin">
                            <i class="material-icons prefix">account_balance</i>
                     
                                <input type="text" name="name" id="name" class="validate" value="{{$user->name}}">
                                <label for="name">Name</label>

                                
                                <span class="{{$errors->has('name') ? 'helper-text red-text' : '' }}">{{$errors->first('name')}}</span>
                            </div>

                            <div class="input-field no-margin">
                            <i class="material-icons prefix">account_balance</i>
                     
                                <input type="text" name="surname" id="surname" class="validate" value="{{ $user->surname }}">
                                <label for="surname">Surname</label>

                                
                                <span class="{{$errors->has('surname') ? 'helper-text red-text' : '' }}">{{$errors->first('surname')}}</span>
                            </div>

                            <div class="input-field no-margin">
                                <i class="material-icons prefix">email</i>
                                <input type="email" name="email" id="email" value="{{$user->email}}">
                                <label for="email">E-mail</label>
                                <span class="{{$errors->has('email') ? 'helper-text red-text' : ''}}">{{$errors->has('email') ? $errors->first('email') : ''}}</span>
                            </div>
                            <br>
                            <div class="input-field no-margin">

                                <select class="selectpicker form-control" name="role" id="role">
                                    <option value="" disabled>Crew member's rank</option>
                                    @foreach($roles as $role)
                                        <option value="{{$role->id}}" {{old('role') ? 'selected' : ''}} {{ $user->role==$role ? 'selected' : '' }} >{{$role->name}}</option>
                                    @endforeach
                                </select>
                                <!-- <label for="role">Rank</label>  -->
                            </div>
                          <br>  
                          <div class="input-field no-margin">

                                <select class="selectpicker form-control" name="ship" id="ship">
                                    <option value="" disabled>Crew member's ship</option>
                                    @foreach($ships as $ship)
                                        <option value="{{$ship->id}}" {{old('ship') ? 'selected' : ''}} {{ $user->ship==$ship ? 'selected' : '' }}>{{$ship->name}}</option>
                                    @endforeach
                                </select>
                                <!-- <label for="role">Rank</label>  -->
                            </div>
                            <!-- <div class="input-field no-margin">

                                <select class="selectpicker form-control" name="ship" id="ship">
                                    <option value="$user->ship_id">{{$user->ship->name}}</option>
                                    @foreach($ships as $ship)
                                        <option value="{{$ship->id}}">{{$ship->name}}</option>
                                    @endforeach
                                </select>
                                <label for="ship">Ship</label>
                            </div> -->
                            <br>
                            <br>  <br><br><br> 
                            @method('PUT')                     
                            @csrf()
                            <button type="submit" class="btn waves-effect waves-light mt-15 col s6 offset-s3 m4 offset-m4 l4 offset-l4 xl4-offset-xl4">Store</button>
                        </form>
                    </div>
                </div>
                

                <div class="card-action">
                    <a href="{{route('admin.users.index')}}">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <h4 class="black-text text-darken-1 center">Crew Members</h4>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">

                <div class="card-body">
                    
                    <table class="responsive-table col s12 m12 l12 xl12">
  <thead class="grey-text text-darken-1">
    <tr>

      <th scope="col">Name</th>
      <th scope="col">E-mail</th>
      <th scope="col">Ship</th>
      <th scope="col">Rank</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    @foreach($users as $user)
    <tr>

      <td>{{$user->name}} {{$user->surname}}</td>
      <td>{{$user->email}}</td>
      <td>{{$user->ship()->first()->name}}</td>
      <td>{{$user->role()->first()->name}}</td>
      <td>

        <a href="{{route('admin.users.edit', $user)}}"class="btn btn-small btn-floating waves=effect waves-light teal lighten-2"><i class="material-icons">list</i></a>
        
        <form action="{{route('admin.users.destroy', $user)}}" method="POST" class="float-left">
            @csrf
            {{method_field('DELETE')}}
            <button type="submit" class="btn btn-floating btn-small waves=effect waves-light red"><i class="material-icons">delete</i></button>
        </form>
      </td>
    </tr>
    @endforeach
  </tbody>
</table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="fixed-action-btn">
    <a class="btn-floating btn-large waves=effect waves-light red" href="{{route('admin.users.create')}}">
        <i class="large material-icons">add</i>
    </a>
</div>
@endsection