routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify'=>true]);

Route::get('/home', 'HomeController@index')->name('home')
;
Route::get('/admin/index', 'Admin\DashboardController@index')->name('admin.index')
;

Route::get('/admin/users/index', 'Admin\UsersController@index')->name('admin.users.index')
;
Route::get('/admin/users/{user}/edit', 'Admin\UsersController@edit')->name('admin.users.edit')
;
Route::put('/admin/users/{user}/update', 'Admin\UsersController@update')->name('admin.users.update')
;
Route::get('/admin/users/destroy', 'Admin\UsersController@destroy')->name('admin.users.destroy')
;
Route::get('/admin/users/create', 'Admin\UsersController@create')->name('admin.users.create')
;

Route::get('/admin/ships/index', 'Admin\ShipsController@index')->name('admin.ships.index')
;
Route::get('/admin/ships/{ship}/edit', 'Admin\ShipsController@edit')->name('admin.ships.edit')
;
Route::put('/admin/ships/{ship}/update', 'Admin\ShipsController@update')->name('admin.ships.update')
;
Route::get('/admin/ships/destroy', 'Admin\ShipsController@destroy')->name('admin.ships.destroy')
;
Route::get('/admin/ships/create', 'Admin\ShipsController@create')->name('admin.ships.create')
;

Route::get('/admin/roles/index', 'Admin\RolesController@index')->name('admin.roles.index')
;
Route::get('/admin/roles/{role}/edit', 'Admin\RolesController@edit')->name('admin.roles.edit')
;
Route::put('/admin/roles/{role}/update', 'Admin\RolesController@update')->name('admin.roles.update')
;
Route::get('/admin/roles/destroy', 'Admin\RolesController@destroy')->name('admin.roles.destroy')
;
Route::get('/admin/roles/create', 'Admin\RolesController@create')->name('admin.roles.create')
;


Route::get('/admin/notifications/create', 'Admin\NotificationsController@create')->name('admin.notifications.create')
;

Route::post('/home/{id}', 'HomeController@markAsRead', function($id){})->name('markAsRead')
;
//Route::get('/password', 'Admin\UsersController@inputPassword')->name('password');

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function(){

	Route::resource('/users', 'UsersController');
	Route::resource('/ships', 'ShipsController');
	Route::resource('/roles', 'RolesController');
	Route::resource('/notifications', 'NotificationsController');

});

app/Ship.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ship extends Model
{
    public function users(){
        return $this->hasMany('App\User');
    }
}

app/Http/Controllers/Admin/ShipsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Ship;

class ShipsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $ships = Ship::all();
        return view ('admin.ships.index')->with('ships', $ships);
    }


    public function create()
    {

        return view('admin.ships.create');
    }

    public function store(Request $request)
    {


        $ship = new Ship();
        $ship->name = $request->input('name');
        $ship->serial_no = $request->input('serial_no');
        
        // if( $request->hasFile('image') ){
            
        //     //get filename with extension
        //     $filenameWithExt = $request->file('image')->getClientOriginalName();
            
        //     //get just filename
        //     $filename = pathInfo($filenameWithExt,PATHINFO_FILENAME);
            
        //     // get just extension
        //     $extension = $request->file('image')->getClientOriginalExtension();
            
        //     $fileNameToStore = $filename.'.'.$extension;
            
        //     //upload the image
        //     $path = $request->file('image')->storeAs('/img/ships',$fileNameToStore);
        //     $ship->image = $fileNameToStore;
        // }
        
  

        $ship->image = time().'.'.request()->file('image')->getClientOriginalExtension();



        request()->file('image')->move(public_path('img/ships'), $ship->image);


        $ship->save();


         return redirect()->route('admin.ships.index');
    }

    public function edit(Ship $ship)
    {

        return view('admin.ships.edit')->with([

            'ship' => $ship


        ]);
    }

    public function update(Request $request, Ship $ship)
    {
        $ship->name = $request->input('name');
        $ship->serial_no = $request->input('serial_no');
        

        // if( $request->hasFile('image') ){
            
        //     //get filename with extension
        //     $filenameWithExt = $request->file('image')->getClientOriginalName();
            
        //     //get just filename
        //     $filename = pathInfo($filenameWithExt,PATHINFO_FILENAME);
            
        //     // get just extension
        //     $extension = $request->file('image')->getClientOriginalExtension();
            
        //     $fileNameToStore = $filename.'.'.$extension;
            
        //     //upload the image
        //     $path = $request->file('image')->storeAs('/img/ships',$fileNameToStore);
        //     $ship->image = $fileNameToStore;
        // }
        
        
        $ship->image = time().'.'.request()->file('image')->getClientOriginalExtension();



        request()->file('image')->move(public_path('img/ships'), $ship->image);


        $ship->save();

        return redirect()->route('admin.ships.index');
    }

    public function destroy(Ship $ship)
    {

        $ship->delete();

        return redirect()->route('admin.ships.index');
    }
}

resources/views/admin/ships/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="card col s12 m8 offset-m2 l8 offset-l2 xl8 offset-xl2 card-mt-15">
                <h4 class="center grey-text text-darken-2 card-title">Add a new ship</h4>
                <div class="card-content" style="width: 50%; margin: 0 auto;">
                    <div class="row">
                       
                        <form action="{{route('admin.ships.store')}}" method="POST" enctype="multipart/form-data">
                            <div class="input-field no-margin">
                            <i class="material-icons prefix">account_balance</i>
                     
                                <input type="text" name="name" id="name" class="validate" value="{{ Request::old('name') ? : '' }}">
                                <label for="name">Name</label>

                                
                                <span class="{{$errors->has('name') ? 'helper-text red-text' : '' }}">{{$errors->first('name')}}</span>
                            </div>
                            <br>
                            <div class="input-field no-margin">
                            <i class="material-icons prefix">account_balance</i>
                     
                                <input type="text" name="serial_no" id="serial_no" class="validate" maxlength="8" value="{{ Request::old('serial_no') ? : '' }}">
                                <label for="serial_no">Serial number</label>

                                
                                <span class="{{$errors->has('serial_no') ? 'helper-text red-text' : '' }}">{{$errors->first('serial_no')}}</span>
                            </div>
                            <br><br>
            
                            
                              <div class="file-field input-field">
                                <div class="btn btn-primary btn-sm float-left">
                                  <span>Choose file</span>
                                  <input type="file" id="image" name="image">
                                </div>
                                <div class="file-path-wrapper">
                                  <input class="file-path validate" type="text" placeholder="Upload your file" value="{{old('image') ? : '' }}">
                                  <span class="{{$errors->has('image') ? 'helper-text red-text' : ''}}">{{$errors->has('image') ? $errors->first('image') : ''}}</span>
                                </div>
                              </div>
                              <br><br>

                                                        
                            @csrf()
                            <br><br>
                            <button type="submit" class="btn waves-effect waves-light mt-15 col s6 offset-s3 m4 offset-m4 l4 offset-l4 xl4-offset-xl4">Add</button>
                        </form>
                    </div>
                </div>
                
                <script>
            $('#image').on('change',function(){
                //get the file name
                var fileName = $(this).val();
                //replace the "Choose a file" label
                $(this).next('.image').html(fileName);
            })
        </script>

                <div class="card-action">
                    <a href="{{route('admin.ships.index')}}">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/ships/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="card col s12 m8 offset-m2 l8 offset-l2 xl8 offset-xl2 card-mt-15">
                <h4 class="center grey-text text-darken-2 card-title">Edit ship {{$ship->name}}</h4>
                <div class="card-content" style="width: 50%; margin: 0 auto;">
                    <div class="row">
                       
                        <form action="{{route('admin.ships.update', $ship)}}" method="POST" enctype="multipart/form-data">
                            <div class="input-field no-margin">
                            <i class="material-icons prefix">account_balance</i>
                     
                                <input type="text" name="name" id="name" class="validate" value="{{ $ship->name }}">
                                <label for="name">Name</label>

                                
                                <span class="{{$errors->has('name') ? 'helper-text red-text' : '' }}">{{$errors->first('name')}}</span>
                            </div>
                            <br>
                            <div class="input-field no-margin">
                            <i class="material-icons prefix">account_balance</i>
                     
                                <input type="text" name="serial_no" id="serial_no" class="validate" value="{{ $ship->serial_no }}">
                                <label for="serial_no">Serial number</label>

                                
                                <span class="{{$errors->has('serial_no') ? 'helper-text red-text' : '' }}">{{$errors->first('serial_no')}}</span>
                            </div>
                            <br><br>

                            
                              <div class="file-field input-field">
                                <div class="btn btn-primary btn-sm float-left">
                                  <span>Choose file</span>
                                  <input type="file" id="image" name="image">
                                </div>
                                <div class="file-path-wrapper">
                                  <input class="file-path validate" type="text" placeholder="Upload your file" value="{{$ship->image}}">
                                  <span class="{{$errors->has('image') ? 'helper-text red-text' : ''}}">{{$errors->has('image') ? $errors->first('image') : ''}}</span>
                                </div>
                              </div>
                              <br><br>

                            @method('PUT')                            
                            @csrf()
                            <br><br>
                            <button type="submit" class="btn waves-effect waves-light mt-15 col s6 offset-s3 m4 offset-m4 l4 offset-l4 xl4-offset-xl4">Store</button>
                        </form>
                    </div>
                </div>
                
                <script>
            $('#image').on('change',function(){
                //get the file name
                var fileName = $(this).val();
                //replace the "Choose a file" label
                $(this).next('.image').html(fileName);
            })
        </script>

                <div class="card-action">
                    <a href="{{route('admin.ships.index')}}">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/ships/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <h4 class="grey-text text-darken-2">Ships</h4>
    
    <div class="row">
  
        <div class="card col s12 m12 l12 xl12">
            <div class="card-content">
                <div class="row">
            
                    <br>
                    <table class="responsive-table col s12 m12 l12 xl12">
                        <thead class="grey-text text-darken-2">
                            <tr>
                                <th class="center" style="width:15%;"></th>
                                <th class="center">Name</th>
                                <th class="center">Serial number</th>
                                <th class="center">Actions</th>
                            </tr>
                        </thead>
                        <tbody id="dept-table">
                            
                            @if($ships->count())
                                @foreach($ships as $ship)
                                    <tr>
                                        <td style="width:15%;" class="center">
                                        <img class="img-fluid" src="{{asset('img/ships/'.$ship->image)}}">
                                    </td>
                                        <td width="23%" class="center">{{$ship->name}}</td>
                                        <td class="center" width="62%" >{{$ship->serial_no}}</td>
                                        <td class="center" width="15%">
                                            <div class="row mb-0">
                                              <div class="col">
              
                                                    <a href="{{route('admin.ships.edit',$ship->id)}}" class="btn btn-floating btn-small waves=effect waves-light orange"><i class="material-icons">mode_edit</i></a>
                                                </div>
                                                <div class="col">

                                                    <form action="{{route('admin.ships.destroy',$ship->id)}}" method="POST">
                    
                                                        @method('DELETE')

                                                        @csrf()
                                                        <button type="submit" class="btn btn-floating btn-small waves=effect waves-light red"><i class="material-icons">delete</i></button>
                                                    </form>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                              
                                <tr>
                                    <td colspan="5"><h6 class="grey-text text-darken-2 center">There are no ships.</h6></td>
                                </tr>
                            @endif

                        </tbody>
                    </table>

                </div>

            </div>
        </div>
        <!-- Card END -->
    </div>
</div>


<div class="fixed-action-btn">
    <a class="btn-floating btn-large waves=effect waves-light red" href="{{route('admin.ships.create')}}">
        <i class="large material-icons">add</i>
    </a>
</div> 
@endsection